// D:\FoundryVTT\Data\modules\fxbus\scripts\util\fxbusMacroUtils.js

/**
 * FX Bus - Macro Utilities
 *
 * Responsibilities:
 * - Build a standalone Foundry macro script that replays an FX Bus "Apply" by emitting a payload via the FX Bus runtime.
 * - Copy macro source text to clipboard with robust fallbacks.
 * - Optional helper to create/update a Macro document.
 *
 * Design constraints:
 * - Macro script must be self-contained and not depend on the GM panel UI.
 * - Macro script must not mutate documents; it should only emit FX messages.
 * - Generated macros should be player-runnable when Macro permissions allow it.
 * - Clipboard operations must be initiated by a user gesture; this module only provides primitives.
 *
 * Compatibility:
 * - Foundry VTT v12+ patterns; intended for v13+.
 */

const MODULE_ID = "fxbus";
const DEFAULT_SOCKET_NAMESPACE = `module.${MODULE_ID}`;

function safeStr(value, fallback = "") {
  const s = String(value ?? "").trim();
  return s.length ? s : fallback;
}

function jsStringLiteral(value) {
  return String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function buildHeaderCommentLines({
  macroName,
  payload,
  generatedAtIso,
  generatedBy,
  fxbusVersion
}) {
  const action = safeStr(payload?.action, "fx.unknown");
  const name = safeStr(macroName, "FX Bus Macro");

  const lines = [
    "/**",
    ` * ${jsStringLiteral(name)}`,
    " *",
    " * Generated by FX Bus GM Control Panel.",
    ` * Action: ${jsStringLiteral(action)}`,
    generatedAtIso ? ` * Generated: ${jsStringLiteral(generatedAtIso)}` : null,
    generatedBy ? ` * User: ${jsStringLiteral(generatedBy)}` : null,
    fxbusVersion ? ` * FX Bus: v${jsStringLiteral(fxbusVersion)}` : null,
    " *",
    " * Behaviour:",
    " * - Visual-only. Does not update Documents.",
    " * - Runs through the local FX Bus runtime.",
    " * - Broadcast policy is handled by FX Bus, not by this macro wrapper.",
    " * - No GM check is applied here; Foundry macro permissions decide who may run it.",
    " */"
  ].filter(Boolean);

  return lines.join("\n");
}

/**
 * Build the source code for a Foundry script macro that emits an FX Bus payload.
 *
 * Important:
 * - FX Bus is runtime-driven through globalThis.fxbus.emit.
 * - Generated macros are intentionally not wrapped in an IIFE.
 * - Generated macros intentionally do not include a GM guard.
 * - Macro ownership/permissions decide who can run the macro.
 * - FX Bus runtime/socket handling decides what happens with the visual payload.
 *
 * Compatibility:
 * - socketNamespace and forceSocket are retained for compatibility with older
 *   call sites, but runtime emission remains the recommended path.
 *
 * @param {string} macroName - Human-friendly macro name for header comments.
 * @param {object} payload - Payload to emit via the FX Bus runtime.
 * @param {object} options
 * @param {string} [options.socketNamespace] - Used only when forceSocket=true.
 * @param {boolean} [options.forceSocket] - If true, emit to socket directly instead of runtime.
 * @param {object} [options.meta]
 * @param {string} [options.meta.generatedAt] - ISO string timestamp.
 * @param {string} [options.meta.generatedBy] - User name.
 * @param {string} [options.meta.fxbusVersion] - Module version string.
 * @returns {string} JavaScript macro source.
 */
export function fxbusBuildMacroSource(
  macroName,
  payload,
  {
    socketNamespace = DEFAULT_SOCKET_NAMESPACE,
    forceSocket = false,
    meta = {}
  } = {}
) {
  const safeName = safeStr(macroName, "FX Bus Macro");

  if (!payload || typeof payload !== "object") {
    throw new Error("fxbusBuildMacroSource: payload must be an object");
  }

  const payloadJson = JSON.stringify(payload, null, 2);

  const runtimeGuard = forceSocket
    ? ""
    : `if (!globalThis.fxbus?.emit) {
  ui.notifications?.error?.("FX Bus runtime not available.");
  throw new Error("FX Bus runtime not available.");
}

`;

  const emitLine = forceSocket
    ? `game.socket.emit(${JSON.stringify(String(socketNamespace))}, payload);`
    : "globalThis.fxbus.emit(payload);";

  const header = buildHeaderCommentLines({
    macroName: safeName,
    payload,
    generatedAtIso: safeStr(meta?.generatedAt, ""),
    generatedBy: safeStr(meta?.generatedBy, ""),
    fxbusVersion: safeStr(meta?.fxbusVersion, "")
  });

  return `${header}

${runtimeGuard}const payload = ${payloadJson};

${emitLine}`;
}

/**
 * Copy text to the system clipboard.
 *
 * Primary:
 * - navigator.clipboard.writeText, where available.
 *
 * Fallback:
 * - document.execCommand("copy") using a temporary textarea.
 *
 * @param {string} text
 * @returns {Promise<void>}
 */
export async function fxbusCopyTextToClipboard(text) {
  const value = String(text ?? "");

  if (!value.length) {
    throw new Error("fxbusCopyTextToClipboard: empty text");
  }

  if (globalThis.navigator?.clipboard?.writeText) {
    await globalThis.navigator.clipboard.writeText(value);
    return;
  }

  const textarea = document.createElement("textarea");
  textarea.value = value;

  textarea.style.position = "fixed";
  textarea.style.top = "-1000px";
  textarea.style.left = "-1000px";
  textarea.style.width = "1px";
  textarea.style.height = "1px";
  textarea.style.opacity = "0";

  document.body.appendChild(textarea);
  textarea.focus();
  textarea.select();

  const ok = document.execCommand("copy");
  document.body.removeChild(textarea);

  if (!ok) throw new Error("fxbusCopyTextToClipboard: execCommand copy failed");
}

/**
 * Optional: Create or update a Foundry Macro document containing the given command.
 *
 * Notes:
 * - This helper is not required if the workflow is clipboard-only.
 * - By default, created macros are global macros.
 * - Macro execution is still controlled by Foundry macro permissions.
 *
 * @param {string} macroName
 * @param {string} macroSource
 * @param {object} options
 * @param {boolean} [options.globalScope] - If true, creates a global macro; else user macro.
 * @returns {Promise<Macro>}
 */
export async function fxbusCreateOrUpdateMacro(
  macroName,
  macroSource,
  { globalScope = true } = {}
) {
  const name = String(macroName ?? "").trim();
  const command = String(macroSource ?? "");

  if (!name.length) throw new Error("fxbusCreateOrUpdateMacro: macroName required");
  if (!command.length) throw new Error("fxbusCreateOrUpdateMacro: macroSource required");

  const existing =
    game.macros?.find?.((m) => m.name === name && m.type === "script") ?? null;

  if (existing) {
    await existing.update({ command });
    return existing;
  }

  return Macro.create({
    name,
    type: "script",
    scope: globalScope ? "global" : "user",
    command,
    ownership: { default: CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER }
  });
}